name: Daily BioSpace News Report

on:
  schedule:
    # Runs at 7:00 AM KST (22:00 UTC previous day)
    - cron: '0 22 * * *'
  workflow_dispatch:  # Allows manual trigger

# Add permissions block
permissions:
  contents: write
  actions: read

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    env:
      TINYURL_API_KEY: ${{ secrets.TINYURL_API_KEY }}
      PYTHONUNBUFFERED: 1
      
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 markdown python-dotenv pytz lxml

    - name: Generate news report
      run: |
        echo "Starting news generation..."
        python -u scripts/generate_news.py
        echo "News generation completed"
      
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add daily_news_report.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update daily news report for $(date +'%Y-%m-%d')" && git push)

    # Make email notification optional
    - name: Send notification
      if: false  # Temporarily disable email notifications
      continue-on-error: true  # Don't fail the workflow if email fails
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{secrets.MAIL_SERVER}}
        server_port: ${{secrets.MAIL_PORT}}
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Daily BioSpace News Report - ${{ steps.date.outputs.date }}
        body: file://daily_news_report.md
        to: ${{secrets.MAIL_TO}}
        from: GitHub Actions 